# Название workflow
name: Testops_parallel

# Переменные окружения
env:
  ALLURE_ENDPOINT: https://demo.qatools.cloud/
  ALLURE_PROJECT_ID: 165
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "allure-results"

# Триггеры для запуска workflow
on:
# пуш и пулл реквест
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

# вручную
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID - service parameter (leave blank)"
        required: false
        default: ""
      ENDPOINT:
        description: "Endpoint"
        required: false
        default: "https://demo.qatools.cloud/"
      BROWSER:
        description: "Browser"
        required: false
        default: "Opera"
      OS:
        description: "OS"
        required: false
        default: "macOS"
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false
        default: ""

jobs:
  autotests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-xdist  # Установка pytest-xdist для распараллеливания тестов
      
      - name: Debug environment variables
        run: |
          echo "ALLURE_ENDPOINT: $allure-endpoint"
          echo "ALLURE_PROJECT_ID: $allure-project-id"
        env:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}
          
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ env.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}
          
      - name: Run tests in parallel
        run: |
          allurectl watch -- pytest -n 4 --alluredir=${ALLURE_RESULTS} --capture=no  # Запуск 4 параллельных процессов
        env:
          ENDPOINT: ${{ github.event.inputs.ENDPOINT }}
          BROWSER: ${{ github.event.inputs.BROWSER }}
          OS: ${{ github.event.inputs.OS }}
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
          ALLURE_RESULTS: ${ALLURE_RESULTS}

      - name: Publish results to Allure TestOps
        run:  |
          ls -la ${ALLURE_RESULTS}
          allurectl publish ${ALLURE_RESULTS} --endpoint ${{ env.ALLURE_ENDPOINT }} --token ${{ secrets.ALLURE_TOKEN }} --project-id ${{ env.ALLURE_PROJECT_ID }}
