# Название workflow
name: Testops

# переменные окружения
env:
  ALLURE_ENDPOINT: https://demo.qatools.cloud/
  ALLURE_PROJECT_ID: 165
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "allure-results"

# Триггеры для запуска workflow
on:
# пуш и пулл реквест
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
     
# вручную    
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID - service parameter (leave blank)"
        required: false
        default: ""
      ENDPOINT:
        description: "Endpoint"
        required: false
        default: "https://demo.qatools.cloud/"
      BROWSER:
        description: Browser
        required: false
        default: "Opera"
      OS:
        description: OS
        required: false
        default: "macOS" 
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false
        default: ""
      BRANCH:
        description: "Git branch (filled automatically)"
        required: true

jobs:
  autotests: 
    name: Run tests
    runs-on: ubuntu-latest
    
    # указываем ветку на которой запускаем воркфлоу
    env:
      BRANCH: ${{ github.ref_name }}
    
    steps:
      - uses: actions/checkout@v3

      # подготовка окружения
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # установка зависисомтей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # отладочные шаги, для проверки работы с переменными
      - name: Debug environment variables
        run: |
          echo "ALLURE_ENDPOINT: $allure-endpoint"
          echo "ALLURE_PROJECT_ID: $allure-project-id"
        env:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

      # устанока allurectl (связующее звено с ТестОпс)
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ env.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

      # создаем директорию для результатов
      - name: Ensure allure-results directory exists
        run: |
          mkdir -p ${ALLURE_RESULTS}

      # запускаем тесты и сразу следим за выполнением
      # отправляем данные в ТестОпс по мере поступления
      - name: Run tests
        run: allurectl watch -- pytest --alluredir=${ALLURE_RESULTS} --capture=no
        env:
          ENDPOINT: ${{ github.event.inputs.ENDPOINT}}
          BROWSER: ${{ github.event.inputs.BROWSER}}
          OS: ${{ github.event.inputs.OS}}
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

      # проверяем если файлы с отчетами
      - name: Check allure-results directory
        if: always()
        run: |
          ls -la ${ALLURE_RESULTS}

      # загружаем файлы в ТестОпс
      #- name: Publish results to Allure TestOps
      #  if: always()
      #  run:  |
      #    allurectl upload ${ALLURE_RESULTS}
      #    #--endpoint ${ALLURE_ENDPOINT} --token ${ALLURE_TOKEN} --project ${ALLURE_PROJECT_ID}
